--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-14-2021   
--------------------------------------------------------
REM INSERTING into ADMINFAQ
SET DEFINE OFF;
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (10,'test04','으으애애','312312132',to_date('21/09/13','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (11,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (12,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (13,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (14,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (15,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (16,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (17,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (18,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (19,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (20,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (21,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (25,'test04','테스트라고했잖아요','테스트라고했잖아요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (26,'test04','테스트라고했잖아요','테스트라고했잖아요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (27,'test04','테스트라고했잖아요','테스트라고했잖아요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (28,'test04','테스트라고했잖아','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (29,'test04','테스트라고했잖아요1','12123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (30,'test04','테스트라고했잖아요','12312',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (31,'test04','테스트라고했잖아요','1232',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (34,'test04','test','test',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (35,'test04','213234','555',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (36,'test04','3252','5252',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (37,'test04','52525','2525252525',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (38,'test04','52525','25522',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (39,'test04','5252525','25252',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (40,'test04','25525252','5252525',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (41,'test04','52522525','2525525',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (63,'test04','21332123','12321123231',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (64,'test04','12312123123','123123123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (65,'test04','213132','21331123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (66,'test04','123123312','213312123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (23,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (22,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (24,'test04','테스트','123123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (32,'test04','테스트','테스추',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (33,'test04','테세','테스투',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (42,'test04','3535','35353535',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (43,'test04','5353','355353',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (44,'test04','53535','33535',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (45,'test04','355353','33553',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (46,'test04','5353','533353',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (47,'test04','353535','3535',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (48,'test04','353535','353535',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (49,'test04','532352','325325',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (50,'test04','135351','135115',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (51,'test04','253235','23523',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (52,'test04','2352','35325235',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (53,'test04','3525','235235',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (54,'test04','2352','23523532',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (55,'test04','235235','23535',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (56,'test04','325','32535235',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (57,'test04','23235235','35325',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (58,'test04','13213212','31212',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (59,'test04','123124','3234',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (60,'test04','132213','23321312',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (61,'test04','123123','123123132123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (62,'test04','132123312','123132312',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (67,'test04','213321','132213132',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINFAQ (ADMINFAQ_NO,ADMINFAQ_NAME,ADMINFAQ_TITLE,ADMINFAQ_CONT,ADMINFAQ_DATE) values (68,'test04','312312','31231223',to_date('21/09/14','RR/MM/DD'));

select adminfaq_no_seq.nextval from dual;

alter sequence adminfaq_no_seq increment by 1;


--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-14-2021   
--------------------------------------------------------
REM INSERTING into ADMINNOTICE
SET DEFINE OFF;
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (30,'test04','2321','21232',to_date('21/09/13','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (31,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (32,'test04','테스트','123132',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (33,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (34,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (35,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (36,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (60,'test04','테스트44','123444',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (61,'test04','테스트입니다','입니다',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (62,'test04','테스트라고해요','후후후후',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (63,'test04','테스트랄까요','테스트라네요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (64,'test04','테스트입니당','입니돠',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (65,'test04','테스트3ㅏ4ㅏ','응',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (68,'test04','테스트!!','많이많이',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (69,'test04','테스트라구요','테스트',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (70,'test04','테스트락어','ㅁㅇㄴㅁ',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (78,'test04','테ㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔㅔ','1232312',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (76,'test04','트슽이빈12312321132312132','132132123132123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (73,'test04','테스트','테스트라고했잖아요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (74,'test04','테스트','123231',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (77,'test04','테스트입니다테스트에요텥스트','셑ㅇㅁㄴㅇㄴㅁ',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (80,'test04','테스트랍니다','테스트',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (81,'test04','테스ㅡ트투투투투투투투투','테스투투투투투투투투투',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (82,'test04','너무길지않은지확인','안기나',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (83,'test04','테스트라고했잖아요','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (84,'test04','테스트라고했잖아요','12',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (87,'test04','테스트라고했잖아요테스트라고했잖아요테스트라고했잖아요','12',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (37,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (38,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (39,'test04','테스트','12321',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (40,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (41,'test04','123','테스트',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (42,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (43,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (44,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (45,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (46,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (47,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (48,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (49,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (50,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (51,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (52,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (53,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (54,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (55,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (56,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (57,'test04','테스트','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (58,'test04','테스트수정','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (59,'test04','테스트수정','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (66,'test04','텥스트','테스투',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (67,'test04','테스트!@!@!','211',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (79,'test04','암ㅁㅇ나ㅏ맘ㅇ안','123123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (85,'test04','테스트라고했잖아요','테스트라고했잖아요',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (86,'test04','테스트라고했잖아','132',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (88,'test04','응애','뿌직',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (89,'test04','테스트','테스트!',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (90,'test04','asdasdda','123312',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (91,'test04','213132123','132132213',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (92,'test04','92','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (93,'test04','32123','123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (94,'test04','123123','123123',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (95,'test04','12312','123132',to_date('21/09/14','RR/MM/DD'));
Insert into ADMINNOTICE (ADMINNOTICE_NO,ADMINNOTICE_NAME,ADMINNOTICE_TITLE,ADMINNOTICE_CONT,ADMINNOTICE_DATE) values (96,'test04','123213','123231213',to_date('21/09/14','RR/MM/DD'));

create sequence adminnotice_no_seq
start with 1
increment by 1
nocache;

select adminnotice_no_seq.nextval from dual;

alter sequence adminnotice_no_seq increment by 1;
